### PR TITLE
v2.14.5

### PR DESCRIPTION
**Pull request by ahmetsait**

### CODE REVIEW

**Comment by aBothe** [comment]
From which codebase did you build these?

**Comment by ahmetsait** [comment]
Ummm... Mono-D master..?

**Comment by aBothe** [comment]
No v.15-version [there](https://github.com/aBothe/Mono-D/blob/master/MonoDevelop.DBinding/MonoDevelop.D.addin.xml) yet :P

**Comment by aBothe** [comment]
could you please commit the v2.14.5-version bump in addin.xml as well then*?
Edit: *into the mono-d source repo

**Comment by ahmetsait** [comment]
Done.

**Comment by aBothe** [comment]
Alright then, thanks! The new version will probably pop up in a few minutes.

**Pull request merged**
